### ISSUE TITLE
Typo: Vector Databases

### ISSUE THREAD

**Issue by OdyAsh** [zahaby/intro-llm-rag#1]
In this page: https://github.com/zahaby/intro-llm-rag/blob/main/main-aspects/vectorstores.md

It is preferable to remove the "is" word below in "in a way that is":

![image](https://github.com/zahaby/intro-llm-rag/assets/66007637/6507648d-673f-420f-8a12-03c5a7f8b3d4)

...

Either way, fantastic and helpful repo. Thanks! 🙌

**Comment by OdyAsh** [comment]
In this page: https://github.com/zahaby/intro-llm-rag/blob/main/main-aspects/vectorstores.md

It is preferable to remove the "is" word below in "in a way that is":

![image](https://github.com/zahaby/intro-llm-rag/assets/66007637/6507648d-673f-420f-8a12-03c5a7f8b3d4)


...

Either way, fantastic and helpful repo. Thanks! 🙌

**Comment by zahaby** [comment]
Thank you very much for thoroughly reviewing the documentation.
